- hosts: all
  roles:
    - bindep
  vars:
    bindep_file: /home/zuul/src/git.openstack.org/openstack/openstack-chef-repo/bindep.txt

- hosts: all
  vars:
    release: 3.1.0
    chefdk: chefdk_{{ release }}-1_amd64.deb
  tasks:
  - name: Fetch chefdk package
    get_url:
      dest: /tmp/{{ chefdk }}
      url: https://packages.chef.io/files/stable/chefdk/{{ release }}/ubuntu/16.04/{{ chefdk }}
  - name: Install chefdk package
    shell: dpkg -i /tmp/{{ chefdk }}
    become: yes

